input {
    kb_layout = us
    kb_variant = intl
    kb_options = compose:caps
    follow_mouse = 1
    sensitivity = 0
    repeat_rate = 30
    repeat_delay = 150

    touchpad {
        natural_scroll = false
        scroll_factor = 0.4
    }
}
